#title: Moselle and Upper-Rhine Algebraic Geometry Seminar
title: MURAGS
email: pieter.belmans@uni.lu
description:
  The Moselle and Upper-Rhine Algebraic Geometry Seminar is a regular seminar,
  jointly organised by several universities in France, Germany, Switzerland and Luxembourg.

plugins:
  - jekyll-redirect-from

# build settings
theme: minima

sass:
  quiet_deps: true
